#!/bin/bash


# A Function to join multiple avi files together

join (){

# $1 is output file, $2 first file to be joined, $3 second file to be joined.

mencoder -oac copy -ovc copy -o $1 $2 $3

echo "Files successfully joined!"

}