#!/bin/bash


# A Function to join multiple avi files together

join (){

# $1 is output file, $2 first file to be joined, $3 second file to be joined.

mencoder -oac copy -ovc copy -o $1 $2 $3

echo "Files successfully joined!"

}


remux(){
	x=$1
	y=${x%.*}
	ffmpeg -i $y.mkv -c:v copy -c:a copy $y.mp4
	rm $1
	echo "File successfully remuxed!"
}